trigger:
- main

pool:
  vmImage: ubuntu-latest
# strategy:
#   matrix:
#    linux:
#     operatingSystem: 'ubuntu-latest'
#    mac:
#     operatingSystem: 'macos-latest'

stages:
- stage: Build
  jobs: 
  - job: BuildJob
    steps:
    - bash: echo Building!
- stage: DevDeploy
  jobs: 
  - deployment: DevDeployJob
    environment: Dev
    strategy: 
      runOnce:
        deploy: 
          steps: 
          - script: echo Deployment for Dev
- stage: QADeploy
  jobs: 
  - deployment: QADeployJob
    environment: QA
    strategy: 
      runOnce:
        deploy: 
          steps: 
          - script: echo Deployment for QA


